### ISSUE TITLE
hiratake.dev のフィードを削除する

### ISSUE THREAD

**Issue by Hiratake** [book000/rss-deliver#324]
hiratake/hiratake-web#667 にて、ウェブサイト側で提供しているRSSフィードに記事本文を含めるよう対応いたしました。
#262 でご対応いただいておりますが、こちらは不要になると思いますので、削除をご検討ください。
（出力されてるRSSフィードの内容が間違ってるとかあれば教えてください）

**Comment by book000** [comment]
了解しました。削除対応します
